### ISSUE TITLE
Dark mode has issues

### ISSUE THREAD

**Issue by toratalet** [T-Ev/TwitterSearchTokenTest#6]
![image](https://user-images.githubusercontent.com/77254572/203724621-24b41dce-1eb2-4201-aef9-2b0cd80c03fe.png)
dark-mode has some issues

_Originally posted by @toratalet in https://github.com/T-Ev/TwitterSearchTokenTest/issues/5#issuecomment-1326074415_

**Comment by toratalet** [comment]
I believe it is a racing condition.
The `search.listBox()` was not ready to add class for it.

When I debug, it is working fine

**Comment by toratalet** [comment]
![image](https://user-images.githubusercontent.com/77254572/203725991-1393ea3d-73f9-4d32-a903-e20a9ce9a6a7.png)

https://github.com/T-Ev/TwitterSearchTokenTest/blob/7a172b6247ff9ba41955805bfe6d23aefb63ed78/script.js#L74


is failing 
css class name might be random?!

**Comment by T-Ev** [comment]
Can you give the fixed script in my PR a try and see if it works for you?

**Comment by T-Ev** [comment]
Awesome Thanks <3 You rock!
